apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob.yaml

namePrefix: concert-discovery-

labels:
- includeSelectors: true
  pairs:
    app: concert-discovery

images:
- name: concert-discovery
  newName: asia-northeast2-docker.pkg.dev/liverty-music-dev/backend/concert-discovery
  newTag: latest

configMapGenerator:
- name: config
  envs:
  - configmap.env
