apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: google-secret-manager
spec:
  provider:
    gcpsm:
      # Replaced by overlay patch per environment
      projectID: TO_REPLACE_BY_OVERLAY
