apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: backend

patches:
# Target server-app after prefixing
- path: serviceaccount_patch.yaml
  target:
    kind: ServiceAccount
    name: server-app

# Global Spot VM patch for all Deployments in dev
- path: spot-vm_patch.yaml
  target:
    kind: Deployment

configMapGenerator:
- name: server-config
  behavior: merge
  envs:
  - server/configmap.env
