apiVersion: v1
kind: ServiceAccount
metadata:
  name: app # Base name matched before namePrefix
  annotations:
    iam.gke.io/gcp-service-account: backend-app@liverty-music-dev.iam.gserviceaccount.com
