apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: server=asia-northeast2-docker.pkg.dev/liverty-music-dev/backend/server, consumer=asia-northeast2-docker.pkg.dev/liverty-music-dev/backend/consumer
    argocd-image-updater.argoproj.io/server.update-strategy: digest
    argocd-image-updater.argoproj.io/server.allow-tags: regexp:^main$
    argocd-image-updater.argoproj.io/consumer.update-strategy: digest
    argocd-image-updater.argoproj.io/consumer.allow-tags: regexp:^main$
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/liverty-music/cloud-provisioning.git
    targetRevision: main
    path: k8s/namespaces/backend/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
