apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-migrations
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/liverty-music/backend.git
    targetRevision: main
    path: k8s/atlas/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: atlas-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
