apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: web-app=asia-northeast2-docker.pkg.dev/liverty-music-dev/frontend/web-app
    argocd-image-updater.argoproj.io/web-app.update-strategy: latest
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/liverty-music/cloud-provisioning.git
    targetRevision: main
    path: k8s/namespaces/frontend/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
