apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-app
  annotations:
    # Requires the GSA created by Pulumi: backend-app@<project-id>.iam.gserviceaccount.com
    # Using placeholder for now, Kustomize overlay should update this or use a configMapGenerator
    iam.gke.io/gcp-service-account: REPLACE_ME_IN_OVERLAY
