apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-app
  namespace: backend
  annotations:
    # Requires the GSA created by Pulumi: liverty-music-backend-app@<project-id>.iam.gserviceaccount.com
    # Using placeholder for now, Kustomize overlay should update this or use a configMapGenerator
    iam.gke.io/gcp-service-account: liverty-music-backend-app@liverty-music-dev.iam.gserviceaccount.com
