apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- httproute.yaml

configurations:
- kustomizeconfig.yaml

namePrefix: web-

labels:
- includeSelectors: true
  pairs:
    app: web

images:
- name: frontend-app
  newName: asia-northeast2-docker.pkg.dev/liverty-music-dev/frontend/app
  newTag: latest
