apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- image-updater.yaml

patches:
# Global Spot VM patches for dev
- path: spot-vm_patch_deployment.yaml
  target:
    kind: Deployment
- path: spot-vm_patch_statefulset.yaml
  target:
    kind: StatefulSet
