apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: eso-sa-patch.yaml
  target:
    kind: ServiceAccount
    name: external-secrets

# Spot VM patch for dev
- target:
    kind: Deployment
    namespace: external-secrets
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector/cloud.google.com~1compute-class
      value: autopilot-spot

# Cost reduction: 1 replica is sufficient for dev
- target:
    kind: Deployment
    name: external-secrets
    namespace: external-secrets
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
