apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: cluster-secret-store-patch.yaml
  target:
    kind: ClusterSecretStore
    name: gcp-secret-manager

# Spot VM patch for dev
- target:
    kind: Deployment
    namespace: external-secrets
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector/cloud.google.com~1compute-class
      value: autopilot-spot
