apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlas-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-manager
    kind: ClusterSecretStore
  target:
    name: atlas-db-credentials
    creationPolicy: Owner
  data:
  - secretKey: postgres-admin-password
    remoteRef:
      key: postgres-admin-password
