apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas-operator

resources:
- external-secret.yaml

helmCharts:
- name: atlas-operator
  repo: oci://ghcr.io/ariga/charts
  version: 0.7.23
  releaseName: atlas-operator
  namespace: atlas-operator
  includeCRDs: true
  valuesFile: values.yaml
