apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- scaledobject.yaml

configurations:
- kustomizeconfig.yaml

namePrefix: consumer-

labels:
- includeSelectors: true
  pairs:
    app: consumer

images:
- name: consumer
  newName: asia-northeast2-docker.pkg.dev/liverty-music-dev/backend/consumer
  newTag: latest

configMapGenerator:
- name: worker-config
  envs:
  - configmap.env
