apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-manager
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
  - secretKey: LASTFM_API_KEY
    remoteRef:
      key: lastfm-api-key
  - secretKey: BLOCKCHAIN_DEPLOYER_PRIVATE_KEY
    remoteRef:
      key: blockchain-deployer-private-key
  - secretKey: BLOCKCHAIN_RPC_URL
    remoteRef:
      key: blockchain-rpc-url
  - secretKey: BUNDLER_API_KEY
    remoteRef:
      key: bundler-api-key
