apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-manager
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
  - secretKey: LASTFM_API_KEY
    remoteRef:
      key: lastfm-api-key
  - secretKey: TICKET_SBT_DEPLOYER_KEY
    remoteRef:
      key: ticket-sbt-deployer-key
  - secretKey: BASE_SEPOLIA_RPC_URL
    remoteRef:
      key: base-sepolia-rpc-url
  - secretKey: BUNDLER_API_KEY
    remoteRef:
      key: bundler-api-key
  - secretKey: VAPID_PRIVATE_KEY
    remoteRef:
      key: vapid-private-key
