serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: argocd-image-updater@liverty-music-dev.iam.gserviceaccount.com

config:
  logLevel: info
  registries:
  - name: GAR
    prefix: asia-northeast2-docker.pkg.dev
    api_url: https://asia-northeast2-docker.pkg.dev
    ping: false

authScripts:
  enabled: true
  scripts:
    auth.sh: |
      #!/bin/sh
      TOKEN=$(wget -qO- --header="Metadata-Flavor: Google" \
        "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" \
        | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p')
      echo "oauth2accesstoken:${TOKEN}"

extraArgs:
- --interval
- 30s

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
