serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: argocd-image-updater@liverty-music-dev.iam.gserviceaccount.com

config:
  logLevel: info
  registries: []

extraArgs:
- --interval
- 30s

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
